language: cpp
os:
  - linux
  - osx

sudo: false

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
#     - llvm-toolchain-precise-3.8
    packages:
      - libstdc++-4.9-dev
      - libboost1.55-all-dev
      - g++-4.9
#     - clang-3.8

env:
  - COMPILER=g++-4.9 GCC_VERSION=4.9
# - COMPILER=clang++-3.8 CLANG_VERSION=3.8

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi

script:
  - ./configure && make && make test
